# Generated by Django 3.2.13 on 2022-06-08 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base_clients', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Clients',
            new_name='Client',
        ),
    ]
