# Generated by Django 3.2.13 on 2022-06-08 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_clients', '0003_order_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
