# Generated by Django 3.2.13 on 2022-06-08 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base_clients', '0004_client_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='name',
            new_name='nom',
        ),
    ]
