# Generated by Django 3.2.13 on 2022-06-08 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_clients', '0005_rename_name_client_nom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='date_naissance',
            field=models.DateField(),
        ),
    ]
