# Generated by Django 3.2.13 on 2022-06-09 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_clients', '0006_alter_client_date_naissance'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remise', models.FloatField()),
                ('duree_remise', models.DurationField()),
            ],
        ),
    ]
