# Generated by Django 3.2.13 on 2022-06-10 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_clients', '0007_promo'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Tricots', 'Tricots'), ('Couture', 'Couture'), ('Canevas', 'Canevas'), ('Machine à coudre', 'Machine à coudre')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='desciption',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
