# Generated by Django 3.2.13 on 2022-06-14 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_clients', '0009_auto_20220614_1333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='desciption',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
