# Generated by Django 3.2.13 on 2022-06-14 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base_clients', '0012_alter_product_desciption'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='prix_total_TTC',
        ),
    ]
