# Generated by Django 3.2.13 on 2022-06-14 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base_clients', '0014_remove_order_facture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='date_creation',
        ),
    ]
